<h1>z2d2 = Zend Framework 1.X + Doctrine 2 Integration</h1>

<a href="<a href="http://www.wjgilmore.com/books/read/easy_php_websites_with_the_zend_framework"><img src="/images/epwzf2e.png" alt="Easy PHP Websites with the Zend Framework" style="border: 0px; float: left; padding-right: 5px;" /></a>

<p>
z2d2 is a companion project to the soon-to-be-released e-book, <a href="http://www.wjgilmore.com/books/read/easy_php_websites_with_the_zend_framework">Easy PHP Websites with the Zend Framework</a>, authored by <a href="http://www.wjgilmore.com/about">W. Jason Gilmore</a> and published by <a href="http://www.wjgilmore.com">WJ Gilmore, LLC</a>.
</p>

<p>
z2d2's primary purpose is to provide readers with an operational Zend Framework-driven website complete with <a href="http://www.doctrine-project.org">Doctrine 2</a> integration. Two sample entity classes are included (complete with a ManyToMany relationship definition), however I am currently leaving it as an exercise to the reader to populate the tables and create the application logic for interacting with the classes. If you're new to Doctrine I recommend <a href="http://www.wjgilmore.com/books/read/easy_php_websites_with_the_zend_framework/code/">downloading Chapter 07, "Integrating Doctrine 2"</a>, which guides you through the creation of entities, shows you how to generate schemas, interact with the database using Doctrine's fantastic object-oriented syntax, and even create your own custom entity repositories.
</p>

<p>
To celebrate the e-book's pending release, you can pre-order it from for <b>just $20</b> from <a href="http://www.wjgilmore.com">WJGilmore.com</a>. When the e-book publishes later this month the price will increase to $30 so preorder your copy now and save. 
</p>

