<?php

namespace Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * Account
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Account extends EntityRepository
{
  
  public function findNewestAccounts() {
   
      $now = new \DateTime("now");
      $oneDayAgo = $now->sub(new \DateInterval('P1D'))
                       ->format('Y-m-d h:i:s');
      $qb = $this->_em->createQueryBuilder();
      $qb->select('a.username')
          ->from('Entities\Account', 'a')
          ->where('a.created >= :date')
          ->setParameter('date', $oneDayAgo);
   
      return $qb->getQuery()->getResult();
  }  
  

}